version: '3.8'

services:
  weibo-album-dl:
    image: weibo-album-dl:latest
    container_name: weibo-album-dl
    restart: unless-stopped
    volumes:
      - ./dl:/dl  # 下载目录
      - ./logs:/app/logs  # 日志目录
    environment:
      WB_DL_ARGS: "-s /dl"